### ISSUE TITLE
On cloning, installing the requirements and running the Saskatoon-ng repo some errors occured

### ISSUE THREAD

**Issue by yokwejuste** [LesFruitsDefendus/saskatoon-ng#165]
## Background
I don't really know how it came about, but recently my Ubuntu 20.04 crashed and the kernel was damaged, 2 days ago I reinstalled the OS but I preferred an upgrade to 21.04.
## Expectations
Obviously, I expected to run the as previously did before the crash but got hocked up.
## what happened
- Finally, I got a first error installing some requirements, mainly at the level of mysqlclient. Below is an illustration or snip of the said error.
![image](https://user-images.githubusercontent.com/71908316/161365492-d69c82ac-63f3-4eb1-b66e-b2736f695cc1.png)
- Then at the level of trying to start the project using mysqlite3, other issues occured.
![image](https://user-images.githubusercontent.com/71908316/161365535-b4470098-ba54-4d50-91f6-eb5d7585352a.png)
## Suggestion
Maybe it's lacking in my requirements or something else? but so far my *pip freeze* gave me these modules
![image](https://user-images.githubusercontent.com/71908316/161365650-f557a571-24ea-4e70-9596-0f2f6d2e9334.png)
![image](https://user-images.githubusercontent.com/71908316/161365630-6575a06b-cd77-4dca-81bc-1b557c11e51a.png)

Can I get any help here?

**Comment by tristanlatr** [comment]
Hi @yokwejuste,

I think you are definitely missing some requirements.

Here is my pip freeze output. after `pip install .`:

```
(ve) tristan@Tristans-MBP saskatoon-ng % pip install .
(ve) tristan@Tristans-MBP saskatoon-ng % pip freeze
asgiref==3.3.4
attrs==20.3.0
certifi==2021.10.8
cffi==1.14.0
charset-normalizer==2.0.12
cryptography==3.4.7
Django==3.2
django-appconf==1.0.4
django-autocomplete-light==3.8.2
django-bootstrap-form==3.4
django-bootstrap3==15.0.0
django-ckeditor==6.0.0
django-crequest==2018.5.11
django-crispy-forms==1.11.2
django-debug-toolbar==3.2.4
django-dotenv==1.4.2
django-extensions==3.1.5
django-filter==2.4.0
django-geojson==3.0.0
django-js-asset==1.2.2
django-leaflet==0.26.0
django-redis==4.12.1
django-rest-knox==4.1.0
django-rosetta==0.9.8
django-select2==7.7.1
djangorestframework==3.12.4
idna==3.3
iniconfig==1.1.1
invoke==1.5.0
jsonfield==3.1.0
mysqlclient==1.4.6
packaging==20.9
Pillow==8.3.2
pluggy==0.13.1
polib==1.1.1
py==1.10.0
pyclean==2.2.0
pycparser==2.20
pyparsing==2.4.7
pytest==6.2.3
pytest-django==4.2.0
pytz==2020.1
redis==3.5.3
requests==2.27.1
Saskatoon @ file:///Users/tristan/Documents/saskatoon-ng
selenium==3.141.0
six==1.15.0
sqlparse==0.3.1
toml==0.10.2
urllib3==1.26.4
```

Hope this helps

**Comment by tristanlatr** [comment]
@yokwejuste did you managed to make work ?

**Comment by yokwejuste** [comment]
> @yokwejuste did you managed to make work ?

Sir now I get q new error, saying saskatoon.saskatoon module doesn't exist

**Comment by tristanlatr** [comment]
@yokwejuste please provide full trace back for your error :)

Make sure you installed correctly Saskatoon with `pip install .`.

Talk to you later,

**Comment by mina-andajos** [comment]
Hi @yokwejuste.
Some dependencies in INSTALL.md are installed with apt.
Are you sure you installed them?
If yes then switch to branch develop and
`pip install . '.[test]'`, everything should work afterwards.

**Comment by richarddushime** [comment]
After  installing the above all worked well 
Though there is another error i corrected in .env file 

i can  try to improve a little bit on the documentation if you give me permission 
Thank you

**Comment by richarddushime** [comment]
asgiref>=3.2.7
cffi>=1.14.0
cryptography>=3.3.2
Django>=3.0.14,<4.0.0
django-geojson==3.0.0
django-leaflet==0.26.0
django-rest-knox==4.1.0
djangorestframework>=3.11.0
django-autocomplete-light>=3.8.2
django-select2
django-ckeditor
django-filter
django-crequest
django-debug-toolbar
django-extensions
jsonfield==3.1.0
mysqlclient==1.4.6
Pillow==8.3.2
pycparser==2.20
pytz==2020.1
six==1.15.0
sqlparse==0.3.1
django-redis
django-dotenv
django-crispy-forms
django-rosetta==0.9.8

**Comment by tristanlatr** [comment]
Thanks @richarddushime for the documentation contribution.

Are we good for closing this issue ?

**Comment by yokwejuste** [comment]
@tristanlatr Still facing same now

**Comment by yokwejuste** [comment]
> Hello i faced also some issues while setting up the project you could try to install the requirements i used here i created them from setup.py
> 
> asgiref>=3.2.7 cffi>=1.14.0 cryptography>=3.3.2 Django>=3.0.14,<4.0.0 django-geojson==3.0.0 django-leaflet==0.26.0 django-rest-knox==4.1.0 djangorestframework>=3.11.0 django-autocomplete-light>=3.8.2 django-select2 django-ckeditor django-filter django-crequest django-debug-toolbar django-extensions jsonfield==3.1.0 mysqlclient==1.4.6 Pillow==8.3.2 pycparser==2.20 pytz==2020.1 six==1.15.0 sqlparse==0.3.1 django-redis django-dotenv django-crispy-forms django-rosetta==0.9.8
> 
> After installing the above all worked well Though there is another error i corrected in .env file
> 
> i can try to improve a little bit on the documentation if you give me permission Thank you

I have the same installed on my local machine but still having an error message
![Screenshot from 2022-04-09 03-49-51](https://user-images.githubusercontent.com/71908316/162553747-c7e3301c-d788-448b-993f-f4f8408abff7.png)

**Comment by yokwejuste** [comment]
Please any suggestion on what i can do so far?

**Comment by richarddushime** [comment]
@yokwejuste if i can see the problem is related to your database settings   check well the name for your databases and other settings  it will work well

**Comment by richarddushime** [comment]
@yokwejuste i can guide through incasse the problem persists  , tell incasse i will be happy to assisst

**Comment by yokwejuste** [comment]
hey @richarddushime ! I don't know if it's the case but will be happy if you provide me some hep
